### ISSUE TITLE
ImplicitSeg can't be installed 

### ISSUE THREAD

**Issue by lunacy-xc** [Project-Splinter/MonoPort#1]
win10
python 3.7
I have both used the pip and git command but I fail to install it .

It has reported such errors:

ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.

Traceback (most recent call last):
  File "Z:\anaconda\envs\XC\lib\distutils\_msvccompiler.py", line 492, in link
    self.spawn([self.linker] + ld_args)
  File "Z:\anaconda\envs\XC\lib\distutils\_msvccompiler.py", line 502, in spawn
    return super().spawn(cmd)
  File "Z:\anaconda\envs\XC\lib\distutils\ccompiler.py", line 910, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "Z:\anaconda\envs\XC\lib\distutils\spawn.py", line 38, in spawn
    _spawn_nt(cmd, search_path, dry_run=dry_run)
  File "Z:\anaconda\envs\XC\lib\distutils\spawn.py", line 81, in _spawn_nt
    "command %r failed with exit status %d" % (cmd, rc))
distutils.errors.DistutilsExecError: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x64\\link.exe' failed with exit status 1181

**Comment by liruilong940607** [comment]
Following up on this issue. [Two more lines](https://github.com/Project-Splinter/ImplicitSegCUDA/blob/master/implicit_seg/functional/__init__.py#L9-L10) need to be comment out if you are trying to avoid using compiled cuda code.
