### ISSUE TITLE
Errors: running RTL/main.py

### ISSUE THREAD

**Issue by dzeitman** [Project-Splinter/MonoPort#17]
Attempted to run in on Google Colab:

Not finding get_cfg_defaults or Monoport 

Traceback (most recent call last):
  File "RTL/main.py", line 19, in <module>
    from monoport.lib.common.config import get_cfg_defaults
ModuleNotFoundError: No module named 'monoport'
Traceback (most recent call last):
  File "RTL/main.py", line 19, in <module>
    from monoport.lib.common.config import get_cfg_defaults
ModuleNotFoundError: No module named 'monoport'
Traceback (most recent call last):
  File "RTL/main.py", line 19, in <module>
    from monoport.lib.common.config import get_cfg_defaults
ModuleNotFoundError: No module named 'monoport'

**Comment by xiangdonglai** [comment]
You probably need to add
```sys.path.append('.')```
if you are using Python 3.7.10.

**Comment by fatpigyin** [comment]
I have the same problem. I also try "sys.path.append('.')" but it will have other problems. Did you solve it? Could someone please help deal with this problem. Thank you very much!

**Comment by andrewnc** [comment]
you can solve this by running `pip install -e .` in the top level
