### ISSUE TITLE
An error message when open the page on a web browser

### ISSUE THREAD

**Issue by zhouliuling** [Project-Splinter/MonoPort#6]
When I've configured it, the running code prompts me to open the web page, but when I open page on the Web Server, I get an error message.I want to know how to solve this problem.Thank you very much.

- Error message:
* Running on http://0.0.0.0:5555/ (Press CTRL+C to quit)
121.248.49.86 - - [25/Aug/2020 16:30:53] "GET / HTTP/1.1" 200 -
Debugging middleware caught exception in streamed response at a point where response headers were already sent.
Traceback (most recent call last):
  File "/home/anaconda3/lib/python3.7/site-packages/werkzeug/wsgi.py", line 506, in __next__
    return self._next()
  File "/home/anaconda3/lib/python3.7/site-packages/werkzeug/wrappers/base_response.py", line 45, in _iter_encoded
    for item in iterable:
  File "/root/project/MonoPort/RTL/main.py", line 476, in main_loop
    renderer = AlbedoRender(width=256, height=256, multi_sample_rate=1)
  File "/root/project/MonoPort/monoport/lib/render/gl/Render.py", line 64, in __init__
    self._init_shader()
  File "/root/project/MonoPort/monoport/lib/render/gl/AlbedoRender.py", line 6, in _init_shader
    self.shader = Shader(vs_file='albedo.vs', fs_file='albedo.fs', gs_file=None)
  File "/root/project/MonoPort/monoport/lib/render/gl/Shader.py", line 35, in __init__
    shaders.compileShader(vp_code, gl.GL_VERTEX_SHADER),
  File "/home/anaconda3/lib/python3.7/site-packages/OpenGL/GL/shaders.py", line 226, in compileShader
    shaderType,
RuntimeError: ("Shader compile failure (0): b'0:1(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.40, 1.00 ES, and 3.00 ES\\n'", [b'#version 330 core\nlayout (location = 0) in vec3 a_Position;\nlayout (location = 1) in vec2 a_TextureCoord;\n\nout vec2 TextureCoord;\n\nuniform mat4 ModelMat;\nuniform mat4 PerspMat;\n\nvoid main()\n{\n\tgl_Position = PerspMat * ModelMat * vec4(a_Position, 1.0);\n    TextureCoord = a_TextureCoord;\n}'], GL_VERTEX_SHADER)

**Comment by YuliangXiu** [comment]
Try to use PyOpenGL with a higher version, ours is 3.1.5.

**Comment by zhouliuling** [comment]
> Try to use PyOpenGL with a higher version, ours is 3.1.5.
I have tried to upgrade the Opengl version to 3.1.5, but this error still exists, I hope to get other guidance. Thank you.

Error:
RuntimeError: ("Shader compile failure (0): b'0:1(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.40, 1.00 ES, and 3.00 ES\n'", [b'#version 330 core\nlayout (location = 0) in vec3 a_Position;\nlayout (location = 1) in vec2 a_TextureCoord;\n\nout vec2 TextureCoord;\n\nuniform mat4 ModelMat;\nuniform mat4 PerspMat;\n\nvoid main()\n{\n\tgl_Position = PerspMat * ModelMat * vec4(a_Position, 1.0);\n TextureCoord = a_TextureCoord;\n}'], GL_VERTEX_SHADER)

**Comment by zhouliuling** [comment]
> Try to use PyOpenGL with a higher version, ours is 3.1.5.

Hello, After I tried to add MESA_L_VERSION_OVERRIDE=3.3 in the running line, my page can be opened without error, but the page is still in the state of "waiting for ··". How can I solve this problem?

![image](https://user-images.githubusercontent.com/50893095/95644077-72d13080-0ae6-11eb-8530-3222f27a4079.png)

The print log is as follows:

```
loading networkG from ./data/PIFu/net_G ...
loading networkC from ./data/PIFu/net_C ...
initialize data streamer ...
Using cache found in /root/.cache/torch/hub/NVIDIA_DeepLearningExamples_torchhub
Using cache found in /root/.cache/torch/hub/NVIDIA_DeepLearningExamples_torchhub
***********************************************
 * Serving Flask app "main" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://0.0.0.0:5555/ (Press CTRL+C to quit)
172.17.0.1 - - [10/Oct/2020 10:36:04] "GET / HTTP/1.1" 200 -
172.17.0.1 - - [10/Oct/2020 10:36:48] "GET /favicon.ico HTTP/1.1" 404 -
0it [00:00, ?it/s]
172.17.0.1 - - [10/Oct/2020 10:36:48] "GET /video_feed HTTP/1.1" 200 -
172.17.0.1 - - [10/Oct/2020 10:40:48] "GET / HTTP/1.1" 200 -
172.17.0.1 - - [10/Oct/2020 10:41:47] "GET /favicon.ico HTTP/1.1" 404 -
0it [00:00, ?it/s]
172.17.0.1 - - [10/Oct/2020 10:41:47] "GET /video_feed HTTP/1.1" 200 -
```

**Comment by jiandandian2** [comment]
@zhouliuling
i have the same problem, and add MESA_L_VERSION_OVERRIDE=3.3, still got OpenGL.GL.shaders.ShaderCompilationError, have u solved it?
![image](https://user-images.githubusercontent.com/33227739/99865973-804eff80-2be8-11eb-8bde-fd144ff910f3.png)

**Comment by jiandandian2** [comment]
@zhouliuling 
i have the same problem, and add MESA_GL_VERSION_OVERRIDE=3.3, the problem was disappeared.
But got another problem:  error 1286  b'invalid framebuffer operation'
have u worked it recently?
![image](https://user-images.githubusercontent.com/33227739/99899628-c342cd00-2ce5-11eb-8c33-bcf6a0cac27d.png)

**Comment by jiandandian2** [comment]
@zhouliuling 
I have solve the problem, the point is vnc server OpenGL connot connet to Nvidia,  i google so many times but never solve the bug.
so u need to run it on your local host, and everything is OK.
![image](https://user-images.githubusercontent.com/33227739/100420238-0d022d80-30c1-11eb-8ecf-dd9dd6ddaa1f.png)

**Comment by baopingli** [comment]
i run ok, but the web shows nothing, and "my render" windows show nothing

**Comment by decadeheart** [comment]
> @zhouliuling
> I have solve the problem, the point is vnc server OpenGL connot connet to Nvidia, i google so many times but never solve the bug.
> so u need to run it on your local host, and everything is OK.
> ![image](https://user-images.githubusercontent.com/33227739/100420238-0d022d80-30c1-11eb-8ecf-dd9dd6ddaa1f.png) 

I also meet the same problem. And I tried it on my local host , it was the same error.Can you tell me how to fix it.
我也遇到了同样的问题。我在我的本地主机上试了一下，还是同样的错误。你能告诉我怎么修理吗?

**Comment by baopingli** [comment]
a usb camera is must

**Comment by shuodehaoa** [comment]
I also meet this problem,the webpage has nothing...what i can do to solve this problem?
file:///C:/Users/gao/Documents/My%20Knowledge/temp/547a6262-cdae-450b-a220-231ae3da3b02/128/index_files/35727437.png

**Comment by shuodehaoa** [comment]
I also meet this problem,the webpage has nothing...what i can do to solve this problem?
![35727437](https://user-images.githubusercontent.com/25994081/114204536-e4057980-998b-11eb-858c-5187241ab7e8.png)
![35766890](https://user-images.githubusercontent.com/25994081/114204557-e8319700-998b-11eb-8614-4e278402d84a.png)

**Comment by helenacorreia** [comment]
@shuodehaoa Have you managed to solve the problem? It's just that I have the same error.
